name: Shell Commands

on: [ push ]

jobs:
  run-shell-command:
  build:
    environment: Debug
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        env:
          DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
        run: echo "WAT"
      - name: multiline script
        env:
          DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
        run: |
          node -v
          npm -v

  
